#pragma once

#define DEFAULT_WINDOW_TITLE "evildojo presents - project rpg v0.000000001"

#define DEFAULT_TARGET_FPS 60

//#define DEFAULT_TARGET_WIDTH 640
//#define DEFAULT_TARGET_HEIGHT 360
#define DEFAULT_TARGET_WIDTH 640
#define DEFAULT_TARGET_HEIGHT 360
#define DEFAULT_SCALE 1

#define DEFAULT_WINDOW_POS_X 0
//#define DEFAULT_WINDOW_POS_X (1920)
#define DEFAULT_WINDOW_POS_Y 0

#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 1.5)
#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 1.5)

#define TXHERO 0
#define TXHEROSHADOW 1
#define TXDIRT 2
#define TXDUNGEONSHEET 3

#define COMPANYSCENE 0
#define TITLESCENE 1
#define GAMEPLAYSCENE 2

#define COMPANYNAME "@evildojo666"
#define COMPANYFILL "   x  x x   "

#define DEFAULT_FONT_PATH "fonts/hack.ttf"
