#pragma once

#define DEFAULT_WINDOW_TITLE "project rpg v0.00000001"

//#define DEFAULT_TARGET_FPS 30
#define DEFAULT_TARGET_FPS 60
#define FRAMEINTERVAL 10

//#define DEFAULT_TARGET_WIDTH 640
//#define DEFAULT_TARGET_HEIGHT 360
//#define DEFAULT_TARGET_WIDTH 640
//#define DEFAULT_TARGET_HEIGHT 360
#define DEFAULT_TARGET_WIDTH 360
#define DEFAULT_TARGET_HEIGHT 640
#define DEFAULT_SCALE 1.5

//#define DEFAULT_WINDOW_POS_X 0
//#define DEFAULT_WINDOW_POS_X 0
//#define DEFAULT_WINDOW_POS_X (1920 / 2)
//#define DEFAULT_WINDOW_POS_X (0)
//#define DEFAULT_WINDOW_POS_Y -5

//#define DEFAULT_WINDOW_WIDTH 1366
//#define DEFAULT_WINDOW_HEIGHT 768
#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * DEFAULT_SCALE) // quarter monitor
#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * DEFAULT_SCALE) // quarter monitor
//#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 3.000) // quarter monitor
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 1.5)
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 1.25) // half monitor
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 2.925) // half monitor
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 3.000) // half monitor
#define DEFAULT_WINDOW_POS_X (1920)
#define DEFAULT_WINDOW_POS_Y 0




#define TXHERO 0
#define TXHEROSHADOW 1

#define TX_DIRT_00 2

#define TXDUNGEONSHEET 3

#define TXHEROWALK 4
#define TXHEROWALKSHADOW 5
#define TXHEROATTACK 6
#define TXHEROATTACKSHADOW 7
#define TXHEROJUMP 8
#define TXHEROJUMPSHADOW 9
#define TXHEROSPINDIE 10
#define TXHEROSPINDIESHADOW 11
#define TXHEROSOULDIE 12
#define TXHEROSOULDIESHADOW 13

#define TXTORCH 14

#define TX_TILE_STONE_00 15
#define TX_TILE_STONE_01 16
#define TX_TILE_STONE_02 17
#define TX_TILE_STONE_03 18
#define TX_TILE_STONE_04 19
#define TX_TILE_STONE_05 20
#define TX_TILE_STONE_06 21
#define TX_TILE_STONE_07 22
#define TX_TILE_STONE_08 23
#define TX_TILE_STONE_09 24
#define TX_TILE_STONE_10 25
#define TX_TILE_STONE_11 26
#define TX_TILE_STONE_12 27
#define TX_TILE_STONE_13 28
#define TX_TILE_STONE_WALL_00 29

#define TX_DIRT_01 30
#define TX_DIRT_02 31

#define TXORCIDLE 32
#define TXORCIDLESHADOW 33
#define TXORCWALK 34
#define TXORCWALKSHADOW 35
#define TXORCATTACK 36
#define TXORCATTACKSHADOW 37

#define TXORCCHARGEDATTACK 38
#define TXORCCHARGEDATTACKSHADOW 39
#define TXORCJUMP 40
#define TXORCJUMPSHADOW 41
#define TXORCDIE 42
#define TXORCDIESHADOW 43
#define TXORCDMG 44
#define TXORCDMGSHADOW 45

#define TXSWORD 46
#define TXSHIELD 47



#define COMPANYSCENE 0
#define TITLESCENE 1
#define GAMEPLAYSCENE 2

#define COMPANYNAME "@evildojo666"
#define COMPANYFILL "   x  x x   "

#define DEFAULT_FONT_PATH "fonts/hack.ttf"


#define DEFAULT_VECTOR_ENTITYID_SIZE 16
#define DEFAULT_HASHTABLE_ENTITYID_ENTITY_SIZE 16
#define DEFAULT_HASHTABLE_ENTITYID_SPRITEGROUP_SIZE 16

// spritegroup context directions
#define SG_CTX_R_D 0
#define SG_CTX_L_D 1
#define SG_CTX_R_U 2
#define SG_CTX_L_U 3
