#pragma once

#define DEFAULT_WINDOW_TITLE "evildojo presents - project rpg v0.000000001"

//#define DEFAULT_TARGET_FPS 30
#define DEFAULT_TARGET_FPS 60
#define FRAMEINTERVAL 10

//#define DEFAULT_TARGET_WIDTH 640
//#define DEFAULT_TARGET_HEIGHT 360
#define DEFAULT_TARGET_WIDTH 640
#define DEFAULT_TARGET_HEIGHT 360
#define DEFAULT_SCALE 1

//#define DEFAULT_WINDOW_POS_X 0
//#define DEFAULT_WINDOW_POS_X (1920)
#define DEFAULT_WINDOW_POS_X (0)
#define DEFAULT_WINDOW_POS_Y 0
//#define DEFAULT_WINDOW_POS_Y -5

#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 2) // quarter monitor
//#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 1.5) // quarter monitor
//#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 1.25) // quarter monitor
//#define DEFAULT_WINDOW_WIDTH (DEFAULT_TARGET_WIDTH * 3.000) // quarter monitor
#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 2)
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 1.5)
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 1.25) // half monitor
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 2.925) // half monitor
//#define DEFAULT_WINDOW_HEIGHT (DEFAULT_TARGET_HEIGHT * 3.000) // half monitor

#define TXHERO 0
#define TXHEROSHADOW 1
#define TXDIRT 2
#define TXDUNGEONSHEET 3
#define TXHEROWALK 4
#define TXHEROWALKSHADOW 5
#define TXHEROATTACK 6
#define TXHEROATTACKSHADOW 7
#define TXHEROJUMP 8
#define TXHEROJUMPSHADOW 9
#define TXHEROSPINDIE 10
#define TXHEROSPINDIESHADOW 11
#define TXHEROSOULDIE 12
#define TXHEROSOULDIESHADOW 13
#define TXTORCH 14

#define COMPANYSCENE 0
#define TITLESCENE 1
#define GAMEPLAYSCENE 2

#define COMPANYNAME "@evildojo666"
#define COMPANYFILL "   x  x x   "

#define DEFAULT_FONT_PATH "fonts/hack.ttf"


#define DEFAULT_VECTOR_ENTITYID_SIZE 1024
#define DEFAULT_HASHTABLE_ENTITYID_ENTITY_SIZE 1024
#define DEFAULT_HASHTABLE_ENTITYID_SPRITEGROUP_SIZE 1024

// spritegroup context directions
#define SG_CTX_R_D 0
#define SG_CTX_L_D 1
#define SG_CTX_R_U 2
#define SG_CTX_L_U 3
