#pragma once


#define SPRITEGROUP_ANIM_IDLE 0
#define SPRITEGROUP_ANIM_WALK 2
#define SPRITEGROUP_ANIM_ATTACK 4
#define SPRITEGROUP_ANIM_JUMP 6
#define SPRITEGROUP_ANIM_SPINDIE 8
#define SPRITEGROUP_ANIM_SOULDIE 10
