#pragma once


#define SPRITEGROUP_ANIM_HUMAN_IDLE 0
#define SPRITEGROUP_ANIM_HUMAN_WALK 2
#define SPRITEGROUP_ANIM_HUMAN_ATTACK 4
#define SPRITEGROUP_ANIM_HUMAN_JUMP 6
#define SPRITEGROUP_ANIM_HUMAN_SPINDIE 8
#define SPRITEGROUP_ANIM_HUMAN_SOULDIE 10


#define SPRITEGROUP_ANIM_ORC_IDLE 0
#define SPRITEGROUP_ANIM_ORC_WALK 2
#define SPRITEGROUP_ANIM_ORC_ATTACK 4
#define SPRITEGROUP_ANIM_ORC_CHARGED_ATTACK 6
#define SPRITEGROUP_ANIM_ORC_JUMP 8
#define SPRITEGROUP_ANIM_ORC_DIE 10
#define SPRITEGROUP_ANIM_ORC_DMG 12


// spritegroup context directions
#define SPRITEGROUP_CONTEXT_R_D 0
#define SPRITEGROUP_CONTEXT_L_D 1
#define SPRITEGROUP_CONTEXT_R_U 2
#define SPRITEGROUP_CONTEXT_L_U 3
