#pragma once

typedef enum {
    AR_MOVE_SUCCESS = 1,
    AR_MOVE_FAIL_BLOCKED_BY_ENTITY = 2,
    AR_MOVE_FAIL_BLOCKED_BY_WALL = 3,
    AR_MOVE_FAIL_OUT_OF_BOUNDS = 4,
    AR_MOVE_FAIL_NO_TILE = 5,
    AR_MOVE_FAIL_UNKNOWN_ENTITY = 6,
    AR_ATTACK_SUCCESS = 7,
    AR_ATTACK_FAIL_OUT_OF_BOUNDS = 8,
    AR_ATTACK_FAIL_NO_TILE = 9,
    AR_PICKUP_SUCCESS = 10,
    AR_PICKUP_FAIL_NO_TILE = 11,
    AR_PICKUP_FAIL_NO_ENTITIES = 12,
    AR_BLOCK_SUCCESS = 13,
    AR_BLOCK_FAIL_UNKNOWN_ENTITY = 14,
    AR_NONE_SUCCESS = 15,
    AR_NONE_FAIL = 16,
    AR_WAIT_SUCCESS = 17,
    AR_WAIT_FAIL = 18,
    AR_WAS_DAMAGED = 19,
} actionresults_t;
