#pragma once

typedef enum {
    CONTROLMODE_CAMERA = 0,
    CONTROLMODE_PLAYER,
    CONTROLMODE_INVENTORY,
    CONTROLMODE_CHEST,
    CONTROLMODE_ACTION_MENU,
    CONTROLMODE_OPTION_MENU,
    //CONTROLMODE_GAMEPLAY_SETTINGS,
    CONTROLMODE_HELP_MENU,
    CONTROLMODE_INTERACTION,
    CONTROLMODE_LEVEL_UP,
    CONTROLMODE_CONFIRM_PROMPT,
    CONTROLMODE_COUNT
} controlmode_t;
