#pragma once

typedef enum
{
    CONTROLMODE_CAMERA = 0,
    CONTROLMODE_PLAYER,
    CONTROLMODE_INVENTORY,
    CONTROLMODE_ACTION_MENU,
    //CONTROLMODE_GAMEPLAY_SETTINGS,
    //CONTROLMODE_HELP,
    CONTROLMODE_COUNT
} controlmode_t;
