#pragma once

#include <stdbool.h>

typedef enum {
    DUNGEON_TILE_TYPE_NONE,
    DUNGEON_TILE_TYPE_FLOOR_DIRT,
    DUNGEON_TILE_TYPE_FLOOR_STONE_00,
    DUNGEON_TILE_TYPE_FLOOR_STONE_01,
    DUNGEON_TILE_TYPE_FLOOR_STONE_02,
    DUNGEON_TILE_TYPE_FLOOR_STONE_03,
    DUNGEON_TILE_TYPE_FLOOR_STONE_04,
    DUNGEON_TILE_TYPE_FLOOR_STONE_05,
    DUNGEON_TILE_TYPE_FLOOR_STONE_06,
    DUNGEON_TILE_TYPE_FLOOR_STONE_07,
    DUNGEON_TILE_TYPE_FLOOR_STONE_08,
    DUNGEON_TILE_TYPE_FLOOR_STONE_09,
    DUNGEON_TILE_TYPE_FLOOR_STONE_10,
    DUNGEON_TILE_TYPE_FLOOR_STONE_11,
    DUNGEON_TILE_TYPE_FLOOR_STONE_12,
    DUNGEON_TILE_TYPE_STONE_WALL_00,
    DUNGEON_TILE_TYPE_STONE_WALL_01,
    DUNGEON_TILE_TYPE_STONE_WALL_02,
    //DUNGEON_TILE_TYPE_STONE_WALL_03,
    //DUNGEON_TILE_TYPE_FLOOR_STONE,
    //DUNGEON_TILE_TYPE_FLOOR_GRASS,
    //DUNGEON_TILE_TYPE_SAND,
    //DUNGEON_TILE_TYPE_SNOW,
    //DUNGEON_TILE_TYPE_ICE,
    //DUNGEON_TILE_TYPE_UPSTAIRS,
    //DUNGEON_TILE_TYPE_DOWNSTAIRS,
    //DUNGEON_TILE_TYPE_WATER,
    //DUNGEON_TILE_TYPE_LAVA,
    //DUNGEON_TILE_TYPE_TREE,
    //DUNGEON_TILE_TYPE_ROCK,
    //DUNGEON_TILE_TYPE_CAVE_WALL,
    //DUNGEON_TILE_TYPE_CAVE_FLOOR,
    //DUNGEON_TILE_TYPE_CAVE_DOOR,
    //DUNGEON_TILE_TYPE_CAVE_UPSTAIRS,
    //DUNGEON_TILE_TYPE_CAVE_DOWNSTAIRS,
    //DUNGEON_TILE_TYPE_CAVE_WATER,
    //DUNGEON_TILE_TYPE_CAVE_LAVA,
    //DUNGEON_TILE_TYPE_CAVE_GRASS,
    //DUNGEON_TILE_TYPE_CAVE_TREE,
    //DUNGEON_TILE_TYPE_CAVE_ROCK,
    //DUNGEON_TILE_TYPE_CAVE_SAND,
    //DUNGEON_TILE_TYPE_CAVE_SNOW,
    //DUNGEON_TILE_TYPE_CAVE_ICE,
    DUNGEON_TILE_TYPE_UNKNOWN,
    DUNGEON_TILE_TYPE_COUNT
} dungeon_tile_type_t;


static inline bool dungeon_tile_is_wall(const dungeon_tile_type_t type) {
    return type >= DUNGEON_TILE_TYPE_STONE_WALL_00 && type <= DUNGEON_TILE_TYPE_STONE_WALL_02;
}

