#pragma once


typedef enum {
    DUNGEON_TILE_TYPE_NONE,
    DUNGEON_TILE_TYPE_STONE_WALL,
    DUNGEON_TILE_TYPE_FLOOR_STONE,
    DUNGEON_TILE_TYPE_FLOOR_DIRT,
    //DUNGEON_TILE_TYPE_FLOOR_GRASS,
    //DUNGEON_TILE_TYPE_SAND,
    //DUNGEON_TILE_TYPE_SNOW,
    //DUNGEON_TILE_TYPE_ICE,
    //DUNGEON_TILE_TYPE_UPSTAIRS,
    //DUNGEON_TILE_TYPE_DOWNSTAIRS,
    //DUNGEON_TILE_TYPE_WATER,
    //DUNGEON_TILE_TYPE_LAVA,
    //DUNGEON_TILE_TYPE_TREE,
    //DUNGEON_TILE_TYPE_ROCK,
    //DUNGEON_TILE_TYPE_CAVE_WALL,
    //DUNGEON_TILE_TYPE_CAVE_FLOOR,
    //DUNGEON_TILE_TYPE_CAVE_DOOR,
    //DUNGEON_TILE_TYPE_CAVE_UPSTAIRS,
    //DUNGEON_TILE_TYPE_CAVE_DOWNSTAIRS,
    //DUNGEON_TILE_TYPE_CAVE_WATER,
    //DUNGEON_TILE_TYPE_CAVE_LAVA,
    //DUNGEON_TILE_TYPE_CAVE_GRASS,
    //DUNGEON_TILE_TYPE_CAVE_TREE,
    //DUNGEON_TILE_TYPE_CAVE_ROCK,
    //DUNGEON_TILE_TYPE_CAVE_SAND,
    //DUNGEON_TILE_TYPE_CAVE_SNOW,
    //DUNGEON_TILE_TYPE_CAVE_ICE,
    DUNGEON_TILE_TYPE_UNKNOWN,
    DUNGEON_TILE_TYPE_COUNT
} dungeon_tile_type_t;
