#pragma once

typedef enum entity_default_action_t {
    ENTITY_DEFAULT_ACTION_NONE = 1,
    ENTITY_DEFAULT_ACTION_RANDOM_MOVE,
    ENTITY_DEFAULT_ACTION_MOVE_TO_TARGET,

    //ENTITY_DEFAULT_ACTION_ATTACK,
    //ENTITY_DEFAULT_ACTION_PICKUP,
    //ENTITY_DEFAULT_ACTION_BLOCK,
    //ENTITY_DEFAULT_ACTION_WAIT,
    ENTITY_DEFAULT_ACTION_COUNT
} entity_default_action_t;
