// entity_action.h
#pragma once

typedef enum {
    ENTITY_ACTION_NONE,
    ENTITY_ACTION_UNKNOWN,
    ENTITY_ACTION_MOVE_LEFT,
    ENTITY_ACTION_MOVE_RIGHT,
    ENTITY_ACTION_MOVE_UP,
    ENTITY_ACTION_MOVE_DOWN,
    ENTITY_ACTION_MOVE_UP_LEFT,
    ENTITY_ACTION_MOVE_UP_RIGHT,
    ENTITY_ACTION_MOVE_DOWN_LEFT,
    ENTITY_ACTION_MOVE_DOWN_RIGHT,
    ENTITY_ACTION_ATTACK_LEFT,
    ENTITY_ACTION_ATTACK_RIGHT,
    ENTITY_ACTION_ATTACK_UP,
    ENTITY_ACTION_ATTACK_DOWN,
    ENTITY_ACTION_ATTACK_UP_LEFT,
    ENTITY_ACTION_ATTACK_UP_RIGHT,
    ENTITY_ACTION_ATTACK_DOWN_LEFT,
    ENTITY_ACTION_ATTACK_DOWN_RIGHT,
    ENTITY_ACTION_MOVE_RANDOM,
    ENTITY_ACTION_ATTACK_RANDOM,
    ENTITY_ACTION_MOVE_PLAYER, // Move towards the player
    ENTITY_ACTION_ATTACK_PLAYER, // Attack player if nearby
    ENTITY_ACTION_WAIT, // Added for future healing
    ENTITY_ACTION_COUNT // Useful for bounds checking
} entity_action_t;
