#pragma once

typedef enum {
    GAMESTATE_FLAG_NONE,
    GAMESTATE_FLAG_PLAYER_INPUT,
    GAMESTATE_FLAG_PLAYER_ANIM,
    GAMESTATE_FLAG_NPC_TURN,
    GAMESTATE_FLAG_NPC_ANIM,
    GAMESTATE_FLAG_NPC_BATCH,
    GAMESTATE_FLAG_COUNT
} gamestate_flag_t;
