#pragma once

#include "img_data.h"
#include "img_data_pack.h"

#define PK_TILE_DIRT_00 ((img_data_pack_t){TILE_DIRT_00_WIDTH, TILE_DIRT_00_HEIGHT, TILE_DIRT_00_FORMAT, TX_DIRT_00, 1, 1, TILE_DIRT_00_DATA})

#define PK_HUMAN_IDLE ((img_data_pack_t){HUMAN_IDLE_WIDTH, HUMAN_IDLE_HEIGHT, HUMAN_IDLE_FORMAT, TX_HERO, 4, 16, HUMAN_IDLE_DATA})
#define PK_HUMAN_IDLE_SHADOW ((img_data_pack_t){HUMAN_IDLE_SHADOW_WIDTH, HUMAN_IDLE_SHADOW_HEIGHT, HUMAN_IDLE_SHADOW_FORMAT, TX_HERO_SHADOW, 4, 16, HUMAN_IDLE_SHADOW_DATA})

#define PK_HUMAN_WALK ((img_data_pack_t){HUMAN_WALK_WIDTH, HUMAN_WALK_HEIGHT, HUMAN_WALK_FORMAT, TX_HERO_WALK, 4, 4, HUMAN_WALK_DATA})
#define PK_HUMAN_WALK_SHADOW ((img_data_pack_t){HUMAN_WALK_SHADOW_WIDTH, HUMAN_WALK_SHADOW_HEIGHT, HUMAN_WALK_SHADOW_FORMAT, TX_HERO_WALK_SHADOW, 4, 4, HUMAN_WALK_SHADOW_DATA})

#define PK_HUMAN_ATTACK ((img_data_pack_t){HUMAN_ATTACK_WIDTH, HUMAN_ATTACK_HEIGHT, HUMAN_ATTACK_FORMAT, TX_HERO_ATTACK, 4, 4, HUMAN_ATTACK_DATA})
#define PK_HUMAN_ATTACK_SHADOW ((img_data_pack_t){HUMAN_ATTACK_SHADOW_WIDTH, HUMAN_ATTACK_SHADOW_HEIGHT, HUMAN_ATTACK_SHADOW_FORMAT, TX_HERO_ATTACK_SHADOW, 4, 4, HUMAN_ATTACK_SHADOW_DATA})

#define PK_HUMAN_JUMP ((img_data_pack_t){HUMAN_JUMP_WIDTH, HUMAN_JUMP_HEIGHT, HUMAN_JUMP_FORMAT, TX_HERO_JUMP, 4, 4, HUMAN_JUMP_DATA})
#define PK_HUMAN_JUMP_SHADOW ((img_data_pack_t){HUMAN_JUMP_SHADOW_WIDTH, HUMAN_JUMP_SHADOW_HEIGHT, HUMAN_JUMP_SHADOW_FORMAT, TX_HERO_JUMP_SHADOW, 4, 4, HUMAN_JUMP_SHADOW_DATA})

#define PK_HUMAN_SPINDIE ((img_data_pack_t){HUMAN_SPINDIE_WIDTH, HUMAN_SPINDIE_HEIGHT, HUMAN_SPINDIE_FORMAT, TX_HERO_SPIN_DIE, 1, 12, HUMAN_SPINDIE_DATA})
#define PK_HUMAN_SPINDIE_SHADOW ((img_data_pack_t){HUMAN_SPINDIE_SHADOW_WIDTH, HUMAN_SPINDIE_SHADOW_HEIGHT, HUMAN_SPINDIE_SHADOW_FORMAT, TX_HERO_SPIN_DIE_SHADOW, 1, 12, HUMAN_SPINDIE_SHADOW_DATA})

#define PK_HUMAN_SOULDIE ((img_data_pack_t){HUMAN_SPINDIE_WIDTH, HUMAN_SPINDIE_HEIGHT, HUMAN_SPINDIE_FORMAT, TX_HERO_SOUL_DIE, 1, 12, HUMAN_SOULDIE_DATA})
#define PK_HUMAN_SOULDIE_SHADOW ((img_data_pack_t){HUMAN_SPINDIE_SHADOW_WIDTH, HUMAN_SPINDIE_SHADOW_HEIGHT, HUMAN_SPINDIE_SHADOW_FORMAT, TX_HERO_SOUL_DIE_SHADOW, 1, 12, HUMAN_SOULDIE_SHADOW_DATA})
