/** @file libgame_defines.h
 *  @brief Shared compile-time constants for versioning, windowing, UI, and gameplay defaults.
 */

#pragma once

#ifndef GAME_INFO_DEFINES
#define GAME_INFO_DEFINES
#define GAME_VERSION "v0.0.6.24"
#define GAME_VERSION_DATE "March 15, 2026"
#define WINDOW_TITLE "@evildojo666 presents: project.rpg"
#endif

#ifndef WINDOW_DEFINES
#define WINDOW_DEFINES
#define DEFAULT_WIN_WIDTH 1920
#define DEFAULT_WIN_HEIGHT 1080
#define DEFAULT_TARGET_WIDTH 1920
#define DEFAULT_TARGET_HEIGHT 1080
#endif

// Alternative window sizes if needed (commented out)
// #define DEFAULT_WIN_WIDTH 360
// #define DEFAULT_WIN_HEIGHT 640
// #define DEFAULT_TARGET_WIDTH 360
// #define DEFAULT_TARGET_HEIGHT 640

#ifndef AUDIO_DEFINES
#define AUDIO_DEFINES
#define DEFAULT_MASTER_VOLUME 1.0f
#define DEFAULT_MUSIC_VOLUME 0.5f
#endif

#ifndef UI_DEFINES
#define UI_DEFINES
#define DEFAULT_MSG_HISTORY_FONT_SIZE 20
#define DEFAULT_MSG_WINDOW_FONT_SIZE 20
#define DEFAULT_LOOK_PANEL_FONT_SIZE 20
#define DEFAULT_HUD_FONT_SIZE 20
#define DEFAULT_HUD_BUFFER_LINE_SIZE 1024
#define DEFAULT_HUD_LINE_COUNT 4
#endif

#ifndef GRAPHICS_DEFINES
#define GRAPHICS_DEFINES
#define DEFAULT_TILE_SIZE_SCALED 32
#define DEFAULT_TILE_SIZE_FLOAT 32.0f
#define DEFAULT_OFFSET -12
#define DEFAULT_TARGET_FPS 60
#define DEFAULT_LOCK 30
#define DEFAULT_TILE_SIZE 8
#define DEFAULT_ZOOM_INCR 1.0f
#define DEFAULT_ZOOM_LEVEL 4.0f
#define FRAMEINTERVAL 10
#endif

#ifndef GAMEPLAY_DEFINES
#define GAMEPLAY_DEFINES
#define DEFAULT_DUNGEONFLOOR_WIDTH 8
#define DEFAULT_DUNGEONFLOOR_HEIGHT 8
#define DEFAULT_ANIM_SPEED 10
#define DEFAULT_CAMERA_ZOOM 10.0f
#endif

#ifndef MEMORY_DEFINES
#define MEMORY_DEFINES
#define DEFAULT_SPRITEGROUPS_SIZE 128
#define SPRITEGROUP_DEFAULT_SIZE 32
#define GAMESTATE_SIZEOFTEXINFOARRAY 2048
#endif

#ifndef SCENE_DEFINES
#define SCENE_DEFINES
#define COMPANYSCENE 0
#define TITLESCENE 1
#define GAMEPLAYSCENE 2
#endif

#define DEFAULT_PAD 20
