#pragma once

#define GAME_VERSION "v0.0.6.5"
#define GAME_VERSION_DATE "February 3, 2026"

#define WINDOW_TITLE "@evildojo666 presents: project.rpg"
//#define DEFAULT_WIN_WIDTH 800
//#define DEFAULT_WIN_HEIGHT 480
//#define DEFAULT_WIN_WIDTH 640
//#define DEFAULT_WIN_HEIGHT 360
#define DEFAULT_WIN_WIDTH 1920
#define DEFAULT_WIN_HEIGHT 1080
//#define DEFAULT_WIN_WIDTH 1280
//#define DEFAULT_WIN_HEIGHT 720
//#define DEFAULT_WIN_WIDTH 960
//#define DEFAULT_WIN_HEIGHT 540

//#define DEFAULT_TARGET_WIDTH 1920
//#define DEFAULT_TARGET_HEIGHT 1080
//#define DEFAULT_TARGET_WIDTH 1280
//#define DEFAULT_TARGET_HEIGHT 720
#define DEFAULT_TARGET_WIDTH 960
#define DEFAULT_TARGET_HEIGHT 540

//#define DEFAULT_TARGET_WIDTH 800
//#define DEFAULT_TARGET_HEIGHT 480
//#define DEFAULT_TARGET_WIDTH 640
//#define DEFAULT_TARGET_HEIGHT 360
//#define SPRITEGROUP_DEFAULT_SIZE 32
#define DEFAULT_TILE_SIZE_SCALED 32
#define DEFAULT_TILE_SIZE_FLOAT 32.0f
#define DEFAULT_OFFSET -12

#define DEFAULT_TARGET_FPS 60
#define FRAMEINTERVAL 10
#define DEFAULT_LOCK 30
#define DEFAULT_TILE_SIZE 8
#define DEFAULT_ZOOM_INCR 1.0f

//-------------------------------------------------------------------------------

//-------------------------------------------------------------------------------

#define COMPANYSCENE 0
#define TITLESCENE 1
#define GAMEPLAYSCENE 2

#define COMPANYNAME "@evildojo666"
#define COMPANYFILL "   x  x x   "

//#define DEFAULT_HASHTABLE_ENTITYID_SPRITEGROUP_SIZE 16

#define DEFAULT_DUNGEONFLOOR_WIDTH 8
#define DEFAULT_DUNGEONFLOOR_HEIGHT 8

#define SPRITEGROUP_DEFAULT_SIZE 32

#define DEFAULT_CAMERA_ZOOM 10.0f

#define DEFAULT_ANIM_SPEED 10

#define DEFAULT_SPRITEGROUPS_SIZE 128
