#pragma once

typedef enum
{
    PROP_NONE,
    PROP_DUNGEON_BANNER_00,
    PROP_DUNGEON_BANNER_01,
    PROP_DUNGEON_BANNER_02,
    PROP_DUNGEON_STATUE_00,
    PROP_DUNGEON_WOODEN_CHAIR_00,
    PROP_DUNGEON_WOODEN_TABLE_00,
    PROP_DUNGEON_WOODEN_TABLE_01,
    PROP_DUNGEON_COUNT,
} proptype_t;
