#pragma once
#define SFX_BAG_OPEN 0
#define SFX_COINS 1
#define SFX_CONFIRM_01 2
#define SFX_EQUIP_01 3
#define SFX_GET_HIT 4
#define SFX_HIT_WET 5
#define SFX_SLASH_ATTACK_HEAVY_1 6
#define SFX_SLASH_ATTACK_HEAVY_2 7
#define SFX_SLASH_ATTACK_HEAVY_3 8
#define SFX_SLASH_ATTACK_LIGHT_1 9
#define SFX_SLASH_ATTACK_LIGHT_2 10
#define SFX_SLASH_ATTACK_LIGHT_3 11
#define SFX_SLASH_ATTACK_SWORD_1 12
#define SFX_SLASH_ATTACK_SWORD_2 13
#define SFX_SLASH_ATTACK_SWORD_3 14
