#pragma once

#define SG_ANIM_NPC_IDLE 0
#define SG_ANIM_NPC_WALK 2
#define SG_ANIM_NPC_ATTACK 4
#define SG_ANIM_NPC_JUMP 6
#define SG_ANIM_NPC_DMG 8
#define SG_ANIM_NPC_SPINDIE 10
#define SG_ANIM_NPC_GUARD_SUCCESS 12
#define SG_ANIM_NPC_SHOT 14

#define SPRITEGROUP_ANIM_NPC_IDLE 0
#define SPRITEGROUP_ANIM_NPC_WALK 2
#define SPRITEGROUP_ANIM_NPC_ATTACK 4
#define SPRITEGROUP_ANIM_NPC_JUMP 6
#define SPRITEGROUP_ANIM_NPC_DMG 8
#define SPRITEGROUP_ANIM_NPC_SPINDIE 10
#define SPRITEGROUP_ANIM_NPC_GUARD_SUCCESS 12
#define SPRITEGROUP_ANIM_NPC_SHOT 14

//#define SPRITEGROUP_ANIM_HUMAN_IDLE 0
//#define SPRITEGROUP_ANIM_HUMAN_WALK 2
//#define SPRITEGROUP_ANIM_HUMAN_ATTACK 4
//#define SPRITEGROUP_ANIM_HUMAN_JUMP 6
//#define SPRITEGROUP_ANIM_HUMAN_DMG 8
//#define SPRITEGROUP_ANIM_HUMAN_SPINDIE 10
//#define SPRITEGROUP_ANIM_HUMAN_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_HUMAN_SHOT 14
//#define SPRITEGROUP_ANIM_HUMAN_GUARD 14
//#define SPRITEGROUP_ANIM_HUMAN_SOULDIE 12
//#define SPRITEGROUP_ANIM_HUMAN_BOW_ATTACK 18

//#define SPRITEGROUP_ANIM_GUARD_WOODEN_SHIELD_FRONT 0
//#define SPRITEGROUP_ANIM_GUARD_WOODEN_SHIELD_BACK 1

//#define SPRITEGROUP_ANIM_ORC_IDLE 0
//#define SPRITEGROUP_ANIM_ORC_WALK 2
//#define SPRITEGROUP_ANIM_ORC_ATTACK 4
//#define SPRITEGROUP_ANIM_ORC_JUMP 6
//#define SPRITEGROUP_ANIM_ORC_DMG 8
//#define SPRITEGROUP_ANIM_ORC_DIE 10
//#define SPRITEGROUP_ANIM_ORC_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_ORC_SHOT 14
//#define SPRITEGROUP_ANIM_ORC_CHARGED_ATTACK 6
//#define SPRITEGROUP_ANIM_ORC_GUARD 14

//#define SPRITEGROUP_ANIM_ELF_IDLE 0
//#define SPRITEGROUP_ANIM_ELF_WALK 2
//#define SPRITEGROUP_ANIM_ELF_ATTACK 4
//#define SPRITEGROUP_ANIM_ELF_JUMP 6
//#define SPRITEGROUP_ANIM_ELF_DMG 8
//#define SPRITEGROUP_ANIM_ELF_SPINDIE 10
//#define SPRITEGROUP_ANIM_ELF_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_ELF_SHOT 14
//#define SPRITEGROUP_ANIM_ELF_SOULDIE 12

//#define SPRITEGROUP_ANIM_DWARF_IDLE 0
//#define SPRITEGROUP_ANIM_DWARF_WALK 2
//#define SPRITEGROUP_ANIM_DWARF_ATTACK 4
//#define SPRITEGROUP_ANIM_DWARF_JUMP 6
//#define SPRITEGROUP_ANIM_DWARF_DMG 8
//#define SPRITEGROUP_ANIM_DWARF_SPINDIE 10
//#define SPRITEGROUP_ANIM_DWARF_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_DWARF_SHOT 14
//#define SPRITEGROUP_ANIM_DWARF_SOULDIE 12

//#define SPRITEGROUP_ANIM_HALFLING_IDLE 0
//#define SPRITEGROUP_ANIM_HALFLING_WALK 2
//#define SPRITEGROUP_ANIM_HALFLING_ATTACK 4
//#define SPRITEGROUP_ANIM_HALFLING_JUMP 6
//#define SPRITEGROUP_ANIM_HALFLING_DMG 8
//#define SPRITEGROUP_ANIM_HALFLING_SPINDIE 10
//#define SPRITEGROUP_ANIM_HALFLING_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_HALFLING_SHOT 14
//#define SPRITEGROUP_ANIM_HALFLING_SOULDIE 12

//#define SPRITEGROUP_ANIM_GOBLIN_IDLE 0
//#define SPRITEGROUP_ANIM_GOBLIN_WALK 2
//#define SPRITEGROUP_ANIM_GOBLIN_ATTACK 4
//#define SPRITEGROUP_ANIM_GOBLIN_JUMP 6
//#define SPRITEGROUP_ANIM_GOBLIN_DMG 8
//#define SPRITEGROUP_ANIM_GOBLIN_SPINDIE 10
//#define SPRITEGROUP_ANIM_GOBLIN_GUARD_SUCCESS 12
//#define SPRITEGROUP_ANIM_GOBLIN_SHOT 14
//#define SPRITEGROUP_ANIM_GOBLIN_SOULDIE 12

#define SG_ANIM_BUCKLER_TILE 0
//#define SG_ANIM_BUCKLER_FRONT 1
//#define SG_ANIM_BUCKLER_BACK 2
#define SG_ANIM_BUCKLER_SUCCESS_FRONT 1
#define SG_ANIM_BUCKLER_SUCCESS_BACK 2

#define SG_ANIM_LONGSWORD_TILE 0
#define SG_ANIM_LONGSWORD_SLASH_F 1
#define SG_ANIM_LONGSWORD_SLASH_B 2

#define SG_ANIM_BOW_TILE 0
#define SG_ANIM_BOW_SHOT_F 1
#define SG_ANIM_BOW_SHOT_B 2

// spritegroup context directions
#define SPRITEGROUP_CONTEXT_R_D 0
#define SPRITEGROUP_CONTEXT_L_D 1
#define SPRITEGROUP_CONTEXT_R_U 2
#define SPRITEGROUP_CONTEXT_L_U 3
