#pragma once

#define SPRITEGROUP_ANIM_HUMAN_IDLE 0
#define SPRITEGROUP_ANIM_HUMAN_WALK 2
#define SPRITEGROUP_ANIM_HUMAN_ATTACK 4
#define SPRITEGROUP_ANIM_HUMAN_JUMP 6
#define SPRITEGROUP_ANIM_HUMAN_DMG 8
#define SPRITEGROUP_ANIM_HUMAN_SPINDIE 10
#define SPRITEGROUP_ANIM_HUMAN_SOULDIE 12
#define SPRITEGROUP_ANIM_HUMAN_GUARD 14
#define SPRITEGROUP_ANIM_HUMAN_GUARD_SUCCESS 16

//#define SPRITEGROUP_ANIM_GUARD_WOODEN_SHIELD_FRONT 0
//#define SPRITEGROUP_ANIM_GUARD_WOODEN_SHIELD_BACK 1

#define SPRITEGROUP_ANIM_ORC_IDLE 0
#define SPRITEGROUP_ANIM_ORC_WALK 2
#define SPRITEGROUP_ANIM_ORC_ATTACK 4
#define SPRITEGROUP_ANIM_ORC_CHARGED_ATTACK 6
#define SPRITEGROUP_ANIM_ORC_JUMP 8
#define SPRITEGROUP_ANIM_ORC_DMG 10
#define SPRITEGROUP_ANIM_ORC_DIE 12

#define SPRITEGROUP_ANIM_ELF_IDLE 0
#define SPRITEGROUP_ANIM_ELF_WALK 2
#define SPRITEGROUP_ANIM_ELF_ATTACK 4
#define SPRITEGROUP_ANIM_ELF_JUMP 6
#define SPRITEGROUP_ANIM_ELF_DMG 8
#define SPRITEGROUP_ANIM_ELF_SPINDIE 10
#define SPRITEGROUP_ANIM_ELF_SOULDIE 12

#define SPRITEGROUP_ANIM_DWARF_IDLE 0
#define SPRITEGROUP_ANIM_DWARF_WALK 2
#define SPRITEGROUP_ANIM_DWARF_ATTACK 4
#define SPRITEGROUP_ANIM_DWARF_JUMP 6
#define SPRITEGROUP_ANIM_DWARF_DMG 8
#define SPRITEGROUP_ANIM_DWARF_SPINDIE 10
#define SPRITEGROUP_ANIM_DWARF_SOULDIE 12

#define SG_ANIM_BUCKLER_TILE 0
#define SG_ANIM_BUCKLER_FRONT 1
#define SG_ANIM_BUCKLER_BACK 2
#define SG_ANIM_BUCKLER_SUCCESS_FRONT 3
#define SG_ANIM_BUCKLER_SUCCESS_BACK 4

// spritegroup context directions
#define SPRITEGROUP_CONTEXT_R_D 0
#define SPRITEGROUP_CONTEXT_L_D 1
#define SPRITEGROUP_CONTEXT_R_U 2
#define SPRITEGROUP_CONTEXT_L_U 3
