#pragma once

// --------------------------------------------------------------------------------
// Tiles
// --------------------------------------------------------------------------------

#define TX_TILES_DIRT_00 0
#define TX_TILES_STONE_00 27
#define TX_TILES_STONE_01 28
#define TX_TILES_STONE_02 29
#define TX_TILES_STONE_03 30
#define TX_TILES_STONE_04 31
#define TX_TILES_STONE_05 32
#define TX_TILES_STONE_06 33
#define TX_TILES_STONE_07 34
#define TX_TILES_STONE_08 35
#define TX_TILES_STONE_09 36
#define TX_TILES_STONE_10 37
#define TX_TILES_STONE_11 38
#define TX_TILES_STONE_12 39
#define TX_TILES_STONEWALL_00 41
#define TX_TILES_STONEWALL_01 42
#define TX_TILES_STONEWALL_02 43
#define TX_TILES_STONEWALL_03 44

#define TX_TILES_STONE_DIRT_UL_00 238
#define TX_TILES_STONE_DIRT_U_00 239
#define TX_TILES_STONE_DIRT_UR_00 240
#define TX_TILES_STONE_DIRT_L_00 241
#define TX_TILES_STONE_DIRT_C_00 242
#define TX_TILES_STONE_DIRT_R_00 243
#define TX_TILES_STONE_DIRT_DL_00 244
#define TX_TILES_STONE_DIRT_D_00 245
#define TX_TILES_STONE_DIRT_DR_00 246

#define TX_TILES_STONE_DIRT_UL_01 247
#define TX_TILES_STONE_DIRT_U_01 248
#define TX_TILES_STONE_DIRT_UR_01 249
#define TX_TILES_STONE_DIRT_L_01 250
#define TX_TILES_STONE_DIRT_C_01 251
#define TX_TILES_STONE_DIRT_R_01 252
#define TX_TILES_STONE_DIRT_DL_01 253
#define TX_TILES_STONE_DIRT_D_01 254
#define TX_TILES_STONE_DIRT_DR_01 255

#define TX_TILES_STONE_DIRT_UL_02 256
#define TX_TILES_STONE_DIRT_U_02 257
#define TX_TILES_STONE_DIRT_UR_02 258
#define TX_TILES_STONE_DIRT_L_02 259
#define TX_TILES_STONE_DIRT_C_02 260
#define TX_TILES_STONE_DIRT_R_02 261
#define TX_TILES_STONE_DIRT_DL_02 262
#define TX_TILES_STONE_DIRT_D_02 263
#define TX_TILES_STONE_DIRT_DR_02 264

#define TX_TILES_STONE_DIRT_UL_03 265
#define TX_TILES_STONE_DIRT_U_03 266
#define TX_TILES_STONE_DIRT_UR_03 267
#define TX_TILES_STONE_DIRT_DL_03 268
#define TX_TILES_STONE_DIRT_D_03 269
#define TX_TILES_STONE_DIRT_DR_03 270

#define TX_TILES_STONE_DIRT_UL_04 271
#define TX_TILES_STONE_DIRT_U_04 272
#define TX_TILES_STONE_DIRT_UR_04 273
#define TX_TILES_STONE_DIRT_DL_04 274
#define TX_TILES_STONE_DIRT_D_04 275
#define TX_TILES_STONE_DIRT_DR_04 276

#define TX_TILES_STONE_DIRT_UL_05 277
#define TX_TILES_STONE_DIRT_U_05 278
#define TX_TILES_STONE_DIRT_UR_05 279
#define TX_TILES_STONE_DIRT_DL_05 280
#define TX_TILES_STONE_DIRT_D_05 281
#define TX_TILES_STONE_DIRT_DR_05 282

#define TX_TILES_GRASS_00 56
#define TX_TILES_GRASS_01 57
#define TX_TILES_GRASS_02 58
#define TX_TILES_GRASS_03 59
#define TX_TILES_GRASS_04 60

#define TX_TILES_GRASS_05 77
#define TX_TILES_GRASS_06 78
#define TX_TILES_GRASS_07 79
#define TX_TILES_GRASS_08 80
#define TX_TILES_GRASS_09 81
#define TX_TILES_GRASS_10 82
#define TX_TILES_GRASS_11 83
#define TX_TILES_GRASS_12 84
#define TX_TILES_GRASS_13 85
#define TX_TILES_GRASS_14 86
#define TX_TILES_GRASS_15 87
#define TX_TILES_GRASS_16 88
#define TX_TILES_GRASS_17 89
#define TX_TILES_GRASS_18 90
#define TX_TILES_GRASS_19 91
#define TX_TILES_DIRT_GRASS_00 92
#define TX_TILES_DIRT_GRASS_01 93
#define TX_TILES_DIRT_GRASS_02 94
#define TX_TILES_DIRT_GRASS_03 95
#define TX_TILES_DIRT_GRASS_04 96
#define TX_TILES_DIRT_GRASS_05 97
#define TX_TILES_DIRT_GRASS_06 98
#define TX_TILES_DIRT_GRASS_07 99
#define TX_TILES_DIRT_GRASS_08 100
#define TX_TILES_DIRT_GRASS_09 101
#define TX_TILES_DIRT_GRASS_10 102
#define TX_TILES_DIRT_GRASS_11 103
#define TX_TILES_DIRT_GRASS_12 104
#define TX_TILES_DIRT_GRASS_13 105
#define TX_TILES_DIRT_GRASS_14 106
#define TX_TILES_WATER_00 107
#define TX_TILES_WATER_01 108
#define TX_TILES_DIRT_06 109
#define TX_TILES_DIRT_07 110
#define TX_TILES_DIRT_08 111

#define TX_TILES_UPSTAIRS_00 118
#define TX_TILES_DOWNSTAIRS_00 119

// --------------------------------------------------------------------------------
// Characters
// --------------------------------------------------------------------------------


#define TX_CHAR_HUMAN_IDLE 1
#define TX_CHAR_HUMAN_IDLE_SHADOW 2
#define TX_CHAR_HUMAN_WALK 3
#define TX_CHAR_HUMAN_WALK_SHADOW 4
#define TX_CHAR_HUMAN_ATTACK 5
#define TX_CHAR_HUMAN_ATTACK_SHADOW 6
#define TX_CHAR_HUMAN_JUMP 7
#define TX_CHAR_HUMAN_JUMP_SHADOW 8
#define TX_CHAR_HUMAN_SPIN_DIE 9
#define TX_CHAR_HUMAN_SPIN_DIE_SHADOW 10
#define TX_CHAR_HUMAN_SOUL_DIE 11
#define TX_CHAR_HUMAN_SOUL_DIE_SHADOW 12
#define TX_CHAR_HUMAN_DMG 75
#define TX_CHAR_HUMAN_DMG_SHADOW 76
#define TX_CHAR_HUMAN_GUARD 66
#define TX_CHAR_HUMAN_GUARD_SHADOW 67
#define TX_CHAR_HUMAN_GUARD_SUCCESS 68
#define TX_CHAR_HUMAN_GUARD_SUCCESS_SHADOW 69
#define TX_CHAR_HUMAN_SHOT 300
#define TX_CHAR_HUMAN_SHOT_SHADOW 301

#define TX_CHAR_ORC_IDLE 13
#define TX_CHAR_ORC_IDLE_SHADOW 14
#define TX_CHAR_ORC_WALK 15
#define TX_CHAR_ORC_WALK_SHADOW 16
#define TX_CHAR_ORC_ATTACK 17
#define TX_CHAR_ORC_ATTACK_SHADOW 18
#define TX_CHAR_ORC_CHARGED_ATTACK 19
#define TX_CHAR_ORC_CHARGED_ATTACK_SHADOW 20
#define TX_CHAR_ORC_JUMP 21
#define TX_CHAR_ORC_JUMP_SHADOW 22
#define TX_CHAR_ORC_DIE 23
#define TX_CHAR_ORC_DIE_SHADOW 24
#define TX_CHAR_ORC_DMG 25
#define TX_CHAR_ORC_DMG_SHADOW 26
#define TX_CHAR_ORC_GUARD 213
#define TX_CHAR_ORC_GUARD_SHADOW 214
#define TX_CHAR_ORC_GUARD_SUCCESS 215
#define TX_CHAR_ORC_GUARD_SUCCESS_SHADOW 216

#define TX_CHAR_DWARF_IDLE 121
#define TX_CHAR_DWARF_IDLE_SHADOW 122
#define TX_CHAR_DWARF_WALK 123
#define TX_CHAR_DWARF_WALK_SHADOW 124
#define TX_CHAR_DWARF_ATTACK 125
#define TX_CHAR_DWARF_ATTACK_SHADOW 126
#define TX_CHAR_DWARF_JUMP 127
#define TX_CHAR_DWARF_JUMP_SHADOW 128
#define TX_CHAR_DWARF_SPIN_DIE 129
#define TX_CHAR_DWARF_SPIN_DIE_SHADOW 130
#define TX_CHAR_DWARF_DMG 133
#define TX_CHAR_DWARF_DMG_SHADOW 134
#define TX_DWARF_GUARD_SUCCESS 287
#define TX_DWARF_GUARD_SUCCESS_SHADOW 288
#define TX_CHAR_DWARF_SHOT 304
#define TX_CHAR_DWARF_SHOT_SHADOW 305

#define TX_CHAR_ELF_IDLE 135
#define TX_CHAR_ELF_IDLE_SHADOW 136
#define TX_CHAR_ELF_WALK 137
#define TX_CHAR_ELF_WALK_SHADOW 138
#define TX_CHAR_ELF_ATTACK 139
#define TX_CHAR_ELF_ATTACK_SHADOW 140
#define TX_CHAR_ELF_JUMP 141
#define TX_CHAR_ELF_JUMP_SHADOW 142
#define TX_CHAR_ELF_SPIN_DIE 143
#define TX_CHAR_ELF_SPIN_DIE_SHADOW 144
#define TX_CHAR_ELF_DMG 147
#define TX_CHAR_ELF_DMG_SHADOW 148
#define TX_CHAR_ELF_GUARD_SUCCESS 289
#define TX_CHAR_ELF_GUARD_SUCCESS_SHADOW 290
#define TX_CHAR_ELF_SHOT 306
#define TX_CHAR_ELF_SHOT_SHADOW 307

#define TX_CHAR_HALFLING_IDLE 149
#define TX_CHAR_HALFLING_IDLE_SHADOW 150
#define TX_CHAR_HALFLING_WALK 151
#define TX_CHAR_HALFLING_WALK_SHADOW 152
#define TX_CHAR_HALFLING_ATTACK 153
#define TX_CHAR_HALFLING_ATTACK_SHADOW 154
#define TX_CHAR_HALFLING_JUMP 155
#define TX_CHAR_HALFLING_JUMP_SHADOW 156
#define TX_CHAR_HALFLING_DMG 157
#define TX_CHAR_HALFLING_DMG_SHADOW 158
#define TX_CHAR_HALFLING_SPIN_DIE 159
#define TX_CHAR_HALFLING_SPIN_DIE_SHADOW 160
#define TX_CHAR_HALFLING_GUARD_SUCCESS 291
#define TX_CHAR_HALFLING_GUARD_SUCCESS_SHADOW 292
#define TX_CHAR_HALFLING_SHOT 308
#define TX_CHAR_HALFLING_SHOT_SHADOW 309

#define TX_CHAR_GOBLIN_IDLE 163
#define TX_CHAR_GOBLIN_IDLE_SHADOW 164
#define TX_CHAR_GOBLIN_WALK 165
#define TX_CHAR_GOBLIN_WALK_SHADOW 166
#define TX_CHAR_GOBLIN_ATTACK 167
#define TX_CHAR_GOBLIN_ATTACK_SHADOW 168
#define TX_CHAR_GOBLIN_JUMP 169
#define TX_CHAR_GOBLIN_JUMP_SHADOW 170
#define TX_CHAR_GOBLIN_DMG 171
#define TX_CHAR_GOBLIN_DMG_SHADOW 172
#define TX_CHAR_GOBLIN_SPIN_DIE 173
#define TX_CHAR_GOBLIN_SPIN_DIE_SHADOW 174
#define TX_CHAR_GOBLIN_GUARD_SUCCESS 293
#define TX_CHAR_GOBLIN_GUARD_SUCCESS_SHADOW 294
#define TX_CHAR_GOBLIN_SHOT 310
#define TX_CHAR_GOBLIN_SHOT_SHADOW 311

//#define TX_ORC_SHOT 302
//#define TX_ORC_SHOT_SHADOW 303


// --------------------------------------------------------------------------------
// Actions
// --------------------------------------------------------------------------------
#define TX_ACTIONS_GUARD_BUCKLER_SUCCESS_FRONT 72
#define TX_ACTIONS_GUARD_BUCKLER_SUCCESS_BACK 73
#define TX_ACTIONS_SLASH_AXE_B 207
#define TX_ACTIONS_SLASH_AXE_F 208
#define TX_ACTION_SLASH_DAGGER_B 209
#define TX_ACTION_SLASH_DAGGER_F 210
#define TX_ACTION_SLASH_SWORD_B 211
#define TX_ACTION_SLASH_SWORD_F 212
#define TX_ACTION_SHOT_BOW_F 312
#define TX_ACTION_SHOT_BOW_B 313
#define TX_ACTION_SHOT_BOW_B_HALFLING_GOBLIN_DWARF 314

#define TX_ACTIONS_GUARD_KITE_SHIELD_SUCCESS_FRONT 297
#define TX_ACTIONS_GUARD_KITE_SHIELD_SUCCESS_BACK 298
#define TX_ACTIONS_GUARD_TOWER_SHIELD_SUCCESS_FRONT 361
#define TX_ACTIONS_GUARD_TOWER_SHIELD_SUCCESS_BACK 362

// --------------------------------------------------------------------------------
// Monsters
// --------------------------------------------------------------------------------

#define TX_MONSTER_BAT_IDLE 177
#define TX_MONSTER_BAT_IDLE_SHADOW 178
#define TX_MONSTER_BAT_ATTACK 179
#define TX_MONSTER_BAT_ATTACK_SHADOW 180
#define TX_MONSTER_BAT_DMG 181
#define TX_MONSTER_BAT_DMG_SHADOW 182
#define TX_MONSTER_BAT_SLEEP 183
#define TX_MONSTER_BAT_SLEEP_SHADOW 184
#define TX_MONSTER_BAT_DIE 316
#define TX_MONSTER_BAT_DIE_SHADOW 317

#define TX_MONSTER_WOLF_IDLE 185
#define TX_MONSTER_WOLF_IDLE_SHADOW 186
#define TX_MONSTER_WOLF_WALK 187
#define TX_MONSTER_WOLF_WALK_SHADOW 188
#define TX_MONSTER_WOLF_ATTACK 189
#define TX_MONSTER_WOLF_ATTACK_SHADOW 190
#define TX_MONSTER_WOLF_DMG 191
#define TX_MONSTER_WOLF_DMG_SHADOW 192
#define TX_MONSTER_WOLF_JUMP 193
#define TX_MONSTER_WOLF_JUMP_SHADOW 194
#define TX_MONSTER_WOLF_DIE 195
#define TX_MONSTER_WOLF_DIE_SHADOW 196

#define TX_MONSTER_WARG_IDLE 318
#define TX_MONSTER_WARG_IDLE_SHADOW 319
#define TX_MONSTER_WARG_WALK 320
#define TX_MONSTER_WARG_WALK_SHADOW 321
#define TX_MONSTER_WARG_ATTACK 322
#define TX_MONSTER_WARG_ATTACK_SHADOW 323
#define TX_MONSTER_WARG_DMG 324
#define TX_MONSTER_WARG_DMG_SHADOW 325
#define TX_MONSTER_WARG_JUMP 326
#define TX_MONSTER_WARG_JUMP_SHADOW 327
#define TX_MONSTER_WARG_DIE 328
#define TX_MONSTER_WARG_DIE_SHADOW 329

#define TX_MONSTER_GREEN_SLIME_IDLE 330
#define TX_MONSTER_GREEN_SLIME_JUMP_ATTACK 332
#define TX_MONSTER_GREEN_SLIME_DMG 334
#define TX_MONSTER_GREEN_SLIME_DIE 336
#define TX_MONSTER_GREEN_SLIME_IDLE_SHADOW 331
#define TX_MONSTER_GREEN_SLIME_JUMP_ATTACK_SHADOW 333
#define TX_MONSTER_GREEN_SLIME_DMG_SHADOW 335
#define TX_MONSTER_GREEN_SLIME_DIE_SHADOW 337


// --------------------------------------------------------------------------------
// Potions
// --------------------------------------------------------------------------------
#define TX_ITEM_POTION_HP_SMALL 201
#define TX_ITEM_POTION_HP_MEDIUM 202
#define TX_ITEM_POTION_HP_LARGE 203

#define TX_ITEM_POTION_MP_SMALL 204
#define TX_ITEM_POTION_MP_MEDIUM 205
#define TX_ITEM_POTION_MP_LARGE 206

// --------------------------------------------------------------------------------
// Doors
// --------------------------------------------------------------------------------
#define TX_DOOR_WOODEN_CLOSED 283
#define TX_DOOR_WOODEN_OPEN 284

// --------------------------------------------------------------------------------
// Doors
// --------------------------------------------------------------------------------
#define TX_ITEM_KEY_BASIC 285

// --------------------------------------------------------------------------------
// Weapons
// --------------------------------------------------------------------------------
#define TX_WEAPON_SWORD_00 120
#define TX_WEAPON_AXE 286
#define TX_WEAPON_BOW 299
#define TX_WEAPON_DAGGER 197
#define TX_WEAPON_TWO_HANDED_SWORD 198
#define TX_WEAPON_ARROW 315
#define TX_WEAPON_WARHAMMER 347
#define TX_WEAPON_WHIP 348

// --------------------------------------------------------------------------------
// Shields
// --------------------------------------------------------------------------------
#define TX_SHIELD_KITE_SHIELD 199
#define TX_SHIELD_WOODEN_TOWER_SHIELD 200
#define TX_SHIELD_BUCKLER 74

// --------------------------------------------------------------------------------
// Spells
// --------------------------------------------------------------------------------
#define TX_SPELL_FIRE_FULL 339
#define TX_SPELL_FIRE_CAST 340
#define TX_SPELL_FIRE_PERSIST 341
#define TX_SPELL_FIRE_END 342

// --------------------------------------------------------------------------------
// Rings
// --------------------------------------------------------------------------------
#define TX_RING_GOLD 343
#define TX_RING_SILVER 344
#define TX_RING_IRON 345

// --------------------------------------------------------------------------------
// Boxes
// --------------------------------------------------------------------------------
#define TX_BOX_WOODEN 346
