#pragma once

typedef enum {
    TILETYPE_NONE = 0,
    TILETYPE_VOID,
    TILETYPE_DIRT_00,
    TILETYPE_DIRT_01,
    TILETYPE_DIRT_02,
    TILETYPE_STONE_00,
    TILETYPE_STONE_01,
    TILETYPE_STONE_02,
    TILETYPE_STONE_03,
    TILETYPE_STONE_04,
    TILETYPE_STONE_05,
    TILETYPE_STONE_06,
    TILETYPE_STONE_07,
    TILETYPE_STONE_08,
    TILETYPE_STONE_09,
    TILETYPE_STONE_10,
    TILETYPE_STONE_11,
    TILETYPE_STONE_12,
    TILETYPE_STONE_13,
    TILETYPE_STONE_WALL_00,
    TILETYPE_COUNT

} tiletype_t;
