#pragma once

#include "libgame_defines.h"
#include "texture_ids.h"


#define TX_PROP_DUNGEON_BANNER_00_COUNT 1
static int TX_PROP_DUNGEON_BANNER_00_KEYS[TX_PROP_DUNGEON_BANNER_00_COUNT] = {TX_PROP_BANNER_00};

#define TX_PROP_DUNGEON_BANNER_01_COUNT 1
static int TX_PROP_DUNGEON_BANNER_01_KEYS[TX_PROP_DUNGEON_BANNER_01_COUNT] = {TX_PROP_BANNER_01};

#define TX_PROP_DUNGEON_BANNER_02_COUNT 1
static int TX_PROP_DUNGEON_BANNER_02_KEYS[TX_PROP_DUNGEON_BANNER_02_COUNT] = {TX_PROP_BANNER_02};

#define TX_PROP_DUNGEON_STATUE_00_COUNT 1
static int TX_PROP_DUNGEON_STATUE_00_KEYS[TX_PROP_DUNGEON_STATUE_00_COUNT] = {TX_PROP_STATUE_00};

#define TX_PROP_DUNGEON_WOODEN_CHAIR_00_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_CHAIR_00_KEYS[TX_PROP_DUNGEON_WOODEN_CHAIR_00_COUNT] = {TX_PROP_WOODEN_CHAIR_00};

#define TX_PROP_DUNGEON_WOODEN_TABLE_00_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_TABLE_00_KEYS[TX_PROP_DUNGEON_WOODEN_TABLE_00_COUNT] = {TX_PROP_WOODEN_TABLE_00};

#define TX_PROP_DUNGEON_WOODEN_TABLE_01_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_TABLE_01_KEYS[TX_PROP_DUNGEON_WOODEN_TABLE_01_COUNT] = {TX_PROP_WOODEN_TABLE_01};
