#pragma once
#include "libgame_defines.h"
#include "texture_ids.h"

// Shields
#define TX_BUCKLER_COUNT 3
static int TX_BUCKLER_KEYS[TX_BUCKLER_COUNT] = {
    TX_BUCKLER,
    TX_ACTIONS_GUARD_BUCKLER_SUCCESS_FRONT,
    TX_ACTIONS_GUARD_BUCKLER_SUCCESS_BACK,
};


#define TX_KITE_SHIELD_COUNT 3
static int TX_KITE_SHIELD_KEYS[TX_KITE_SHIELD_COUNT] = {
    TX_KITE_SHIELD,
    TX_GUARD_KITE_SHIELD_SUCCESS_FRONT,
    TX_GUARD_KITE_SHIELD_SUCCESS_BACK,
};


#define TX_TOWER_SHIELD_COUNT 3
static int TX_TOWER_SHIELD_KEYS[TX_TOWER_SHIELD_COUNT] = {
    TX_WOODEN_TOWER_SHIELD,
    TX_GUARD_TOWER_SHIELD_SUCCESS_FRONT,
    TX_GUARD_TOWER_SHIELD_SUCCESS_BACK,
};
