#pragma once

#include "libgame_defines.h"

#define TX_HUMAN_KEY_COUNT 16
static int TX_HUMAN_KEYS[TX_HUMAN_KEY_COUNT] = {TX_HUMAN_IDLE,
                                                TX_HUMAN_IDLE_SHADOW,
                                                TX_HUMAN_WALK,
                                                TX_HUMAN_WALK_SHADOW,
                                                TX_HUMAN_ATTACK,
                                                TX_HUMAN_ATTACK_SHADOW,
                                                TX_HUMAN_JUMP,
                                                TX_HUMAN_JUMP_SHADOW,
                                                TX_HUMAN_DMG,
                                                TX_HUMAN_DMG_SHADOW,
                                                TX_HUMAN_SPIN_DIE,
                                                TX_HUMAN_SPIN_DIE_SHADOW,
                                                TX_HUMAN_GUARD_SUCCESS,
                                                TX_HUMAN_GUARD_SUCCESS_SHADOW,
                                                TX_HUMAN_SHOT,
                                                TX_HUMAN_SHOT_SHADOW};
//TX_HUMAN_SOUL_DIE,
//TX_HUMAN_SOUL_DIE_SHADOW,
//TX_HUMAN_GUARD,
//TX_HUMAN_GUARD_SHADOW,

#define TX_ORC_KEY_COUNT 16
static int TX_ORC_KEYS[TX_ORC_KEY_COUNT] = {
    TX_ORC_IDLE,
    TX_ORC_IDLE_SHADOW,
    TX_ORC_WALK,
    TX_ORC_WALK_SHADOW,
    TX_ORC_ATTACK,
    TX_ORC_ATTACK_SHADOW,
    TX_ORC_JUMP,
    TX_ORC_JUMP_SHADOW,
    TX_ORC_DMG,
    TX_ORC_DMG_SHADOW,
    TX_ORC_DIE,
    TX_ORC_DIE_SHADOW,
    TX_ORC_GUARD_SUCCESS,
    TX_ORC_GUARD_SUCCESS_SHADOW,
    TX_ORC_SHOT,
    TX_ORC_SHOT_SHADOW,
};
//TX_ORC_GUARD,
//TX_ORC_GUARD_SHADOW,
//TX_ORC_CHARGED_ATTACK,
//TX_ORC_CHARGED_ATTACK_SHADOW,

#define TX_ELF_KEY_COUNT 16
static int TX_ELF_KEYS[TX_ELF_KEY_COUNT] = {
    TX_ELF_IDLE,
    TX_ELF_IDLE_SHADOW,
    TX_ELF_WALK,
    TX_ELF_WALK_SHADOW,
    TX_ELF_ATTACK,
    TX_ELF_ATTACK_SHADOW,
    TX_ELF_JUMP,
    TX_ELF_JUMP_SHADOW,
    TX_ELF_DMG,
    TX_ELF_DMG_SHADOW,
    TX_ELF_SPIN_DIE,
    TX_ELF_SPIN_DIE_SHADOW,
    TX_ELF_GUARD_SUCCESS,
    TX_ELF_GUARD_SUCCESS_SHADOW,
    TX_ELF_SHOT,
    TX_ELF_SHOT_SHADOW,
};
//TX_ELF_SOUL_DIE,
//TX_ELF_SOUL_DIE_SHADOW,

#define TX_DWARF_KEY_COUNT 16
static int TX_DWARF_KEYS[TX_DWARF_KEY_COUNT] = {
    TX_DWARF_IDLE,
    TX_DWARF_IDLE_SHADOW,
    TX_DWARF_WALK,
    TX_DWARF_WALK_SHADOW,
    TX_DWARF_ATTACK,
    TX_DWARF_ATTACK_SHADOW,
    TX_DWARF_JUMP,
    TX_DWARF_JUMP_SHADOW,
    TX_DWARF_DMG,
    TX_DWARF_DMG_SHADOW,
    TX_DWARF_SPIN_DIE,
    TX_DWARF_SPIN_DIE_SHADOW,
    TX_DWARF_GUARD_SUCCESS,
    TX_DWARF_GUARD_SUCCESS_SHADOW,
    TX_DWARF_SHOT,
    TX_DWARF_SHOT_SHADOW,
};
//TX_DWARF_SOUL_DIE,
//TX_DWARF_SOUL_DIE_SHADOW,

#define TX_HALFLING_KEY_COUNT 16
static int TX_HALFLING_KEYS[TX_HALFLING_KEY_COUNT] = {
    TX_HALFLING_IDLE,
    TX_HALFLING_IDLE_SHADOW,
    TX_HALFLING_WALK,
    TX_HALFLING_WALK_SHADOW,
    TX_HALFLING_ATTACK,
    TX_HALFLING_ATTACK_SHADOW,
    TX_HALFLING_JUMP,
    TX_HALFLING_JUMP_SHADOW,
    TX_HALFLING_DMG,
    TX_HALFLING_DMG_SHADOW,
    TX_HALFLING_SPIN_DIE,
    TX_HALFLING_SPIN_DIE_SHADOW,
    TX_HALFLING_GUARD_SUCCESS,
    TX_HALFLING_GUARD_SUCCESS_SHADOW,
    TX_HALFLING_SHOT,
    TX_HALFLING_SHOT_SHADOW,
};

#define TX_GOBLIN_KEY_COUNT 16
static int TX_GOBLIN_KEYS[TX_GOBLIN_KEY_COUNT] = {
    TX_GOBLIN_IDLE,
    TX_GOBLIN_IDLE_SHADOW,
    TX_GOBLIN_WALK,
    TX_GOBLIN_WALK_SHADOW,
    TX_GOBLIN_ATTACK,
    TX_GOBLIN_ATTACK_SHADOW,
    TX_GOBLIN_JUMP,
    TX_GOBLIN_JUMP_SHADOW,
    TX_GOBLIN_DMG,
    TX_GOBLIN_DMG_SHADOW,
    TX_GOBLIN_SPIN_DIE,
    TX_GOBLIN_SPIN_DIE_SHADOW,
    TX_GOBLIN_GUARD_SUCCESS,
    TX_GOBLIN_GUARD_SUCCESS_SHADOW,
    TX_GOBLIN_SHOT,
    TX_GOBLIN_SHOT_SHADOW,
};

#define TX_WOLF_KEY_COUNT 12
static int TX_WOLF_KEYS[TX_WOLF_KEY_COUNT] = {
    TX_WOLF_IDLE,
    TX_WOLF_IDLE_SHADOW,
    TX_WOLF_WALK,
    TX_WOLF_WALK_SHADOW,
    TX_WOLF_ATTACK,
    TX_WOLF_ATTACK_SHADOW,
    TX_WOLF_JUMP,
    TX_WOLF_JUMP_SHADOW,
    TX_WOLF_DMG,
    TX_WOLF_DMG_SHADOW,
    TX_WOLF_DIE,
    TX_WOLF_DIE_SHADOW,
};

// Weapons

#define TX_LONG_SWORD_KEY_COUNT 3
static int TX_LONG_SWORD_KEYS[TX_LONG_SWORD_KEY_COUNT] = {TX_LONG_SWORD_00, TX_ACTION_SLASH_SWORD_F, TX_ACTION_SLASH_SWORD_B};

#define TX_DAGGER_KEY_COUNT 3
static int TX_DAGGER_KEYS[TX_DAGGER_KEY_COUNT] = {TX_DAGGER, TX_ACTION_SLASH_DAGGER_F, TX_ACTION_SLASH_DAGGER_B};

#define TX_AXE_KEY_COUNT 3
static int TX_AXE_KEYS[TX_AXE_KEY_COUNT] = {TX_AXE, TX_ACTION_SLASH_AXE_F, TX_ACTION_SLASH_AXE_B};

#define TX_BOW_KEY_COUNT 4
static int TX_BOW_KEYS[TX_BOW_KEY_COUNT] = {TX_BOW, TX_ACTION_SHOT_BOW_F, TX_ACTION_SHOT_BOW_B, TX_ACTION_SHOT_BOW_B_HALFLING_GOBLIN_DWARF};

#define TX_ARROW_KEY_COUNT 1
static int TX_ARROW_KEYS[TX_ARROW_KEY_COUNT] = {TX_ARROW};

// Shields

#define TX_BUCKLER_KEY_COUNT 3
static int TX_BUCKLER_KEYS[TX_BUCKLER_KEY_COUNT] = {
    TX_BUCKLER,
    TX_GUARD_BUCKLER_SUCCESS_FRONT,
    TX_GUARD_BUCKLER_SUCCESS_BACK,
};
//TX_GUARD_BUCKLER_FRONT,
//TX_GUARD_BUCKLER_BACK,

// Potions
#define TX_POTION_HP_SMALL_KEY_COUNT 1
static int TX_POTION_HP_SMALL_KEYS[TX_POTION_HP_SMALL_KEY_COUNT] = {TX_POTION_HP_SMALL};

#define TX_POTION_HP_MEDIUM_KEY_COUNT 1
static int TX_POTION_HP_MEDIUM_KEYS[TX_POTION_HP_MEDIUM_KEY_COUNT] = {TX_POTION_HP_MEDIUM};

#define TX_POTION_HP_LARGE_KEY_COUNT 1
static int TX_POTION_HP_LARGE_KEYS[TX_POTION_HP_LARGE_KEY_COUNT] = {TX_POTION_HP_LARGE};

#define TX_POTION_MP_SMALL_KEY_COUNT 1
static int TX_POTION_MP_SMALL_KEYS[TX_POTION_MP_SMALL_KEY_COUNT] = {TX_POTION_MP_SMALL};

#define TX_POTION_MP_MEDIUM_KEY_COUNT 1
static int TX_POTION_MP_MEDIUM_KEYS[TX_POTION_MP_MEDIUM_KEY_COUNT] = {TX_POTION_MP_MEDIUM};

#define TX_POTION_MP_LARGE_KEY_COUNT 1
static int TX_POTION_MP_LARGE_KEYS[TX_POTION_MP_LARGE_KEY_COUNT] = {TX_POTION_MP_LARGE};

#define TX_WOODEN_DOOR_KEY_COUNT 2
static int TX_WOODEN_DOOR_KEYS[TX_WOODEN_DOOR_KEY_COUNT] = {TX_WOODEN_DOOR_CLOSED, TX_WOODEN_DOOR_OPEN};

#define TX_KEY_BASIC_KEY_COUNT 1
static int TX_KEY_BASIC_KEYS[TX_KEY_BASIC_KEY_COUNT] = {TX_KEY_BASIC};
