/** @file tx_keys_props.h
 *  @brief Texture-key arrays for prop entities.
 */

#pragma once

#include "libgame_defines.h"
#include "texture_ids.h"

/// @brief Texture-key arrays for individual prop variants used by prop spritegroups.
#define TX_PROP_DUNGEON_BANNER_00_COUNT 1
static int TX_PROP_DUNGEON_BANNER_00_KEYS[TX_PROP_DUNGEON_BANNER_00_COUNT] = {TX_PROP_BANNER_00};

#define TX_PROP_DUNGEON_BANNER_01_COUNT 1
static int TX_PROP_DUNGEON_BANNER_01_KEYS[TX_PROP_DUNGEON_BANNER_01_COUNT] = {TX_PROP_BANNER_01};

#define TX_PROP_DUNGEON_BANNER_02_COUNT 1
static int TX_PROP_DUNGEON_BANNER_02_KEYS[TX_PROP_DUNGEON_BANNER_02_COUNT] = {TX_PROP_BANNER_02};

#define TX_PROP_DUNGEON_STATUE_00_COUNT 1
static int TX_PROP_DUNGEON_STATUE_00_KEYS[TX_PROP_DUNGEON_STATUE_00_COUNT] = {TX_PROP_STATUE_00};

#define TX_PROP_DUNGEON_TORCH_00_COUNT 1
static int TX_PROP_DUNGEON_TORCH_00_KEYS[TX_PROP_DUNGEON_TORCH_00_COUNT] = {TX_PROP_TORCH_00};

#define TX_PROP_DUNGEON_CANDLE_00_COUNT 1
static int TX_PROP_DUNGEON_CANDLE_00_KEYS[TX_PROP_DUNGEON_CANDLE_00_COUNT] = {TX_PROP_CANDLE_00};

#define TX_PROP_DUNGEON_JAR_00_COUNT 1
static int TX_PROP_DUNGEON_JAR_00_KEYS[TX_PROP_DUNGEON_JAR_00_COUNT] = {TX_PROP_JAR_00};

#define TX_PROP_DUNGEON_PLATE_00_COUNT 1
static int TX_PROP_DUNGEON_PLATE_00_KEYS[TX_PROP_DUNGEON_PLATE_00_COUNT] = {TX_PROP_PLATE_00};

#define TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_EMPTY_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_EMPTY_KEYS[TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_EMPTY_COUNT] = {TX_PROP_WOODEN_BARREL_OPEN_TOP_EMPTY};

#define TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_WATER_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_WATER_KEYS[TX_PROP_DUNGEON_WOODEN_BARREL_OPEN_TOP_WATER_COUNT] = {TX_PROP_WOODEN_BARREL_OPEN_TOP_WATER};

#define TX_PROP_DUNGEON_WOODEN_CHAIR_00_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_CHAIR_00_KEYS[TX_PROP_DUNGEON_WOODEN_CHAIR_00_COUNT] = {TX_PROP_WOODEN_CHAIR_00};

#define TX_PROP_DUNGEON_WOODEN_TABLE_00_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_TABLE_00_KEYS[TX_PROP_DUNGEON_WOODEN_TABLE_00_COUNT] = {TX_PROP_WOODEN_TABLE_00};

#define TX_PROP_DUNGEON_WOODEN_TABLE_01_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_TABLE_01_KEYS[TX_PROP_DUNGEON_WOODEN_TABLE_01_COUNT] = {TX_PROP_WOODEN_TABLE_01};

#define TX_PROP_DUNGEON_WOODEN_SIGN_COUNT 1
static int TX_PROP_DUNGEON_WOODEN_SIGN_KEYS[TX_PROP_DUNGEON_WOODEN_SIGN_COUNT] = {TX_PROP_WOODEN_SIGN};
