#pragma once
#include "libgame_defines.h"

// Potions
#define TX_POTION_HP_SMALL_COUNT 1
static int TX_POTION_HP_SMALL_KEYS[TX_POTION_HP_SMALL_COUNT] = {TX_POTION_HP_SMALL};

#define TX_POTION_HP_MEDIUM_COUNT 1
static int TX_POTION_HP_MEDIUM_KEYS[TX_POTION_HP_MEDIUM_COUNT] = {TX_POTION_HP_MEDIUM};

#define TX_POTION_HP_LARGE_COUNT 1
static int TX_POTION_HP_LARGE_KEYS[TX_POTION_HP_LARGE_COUNT] = {TX_POTION_HP_LARGE};

#define TX_POTION_MP_SMALL_COUNT 1
static int TX_POTION_MP_SMALL_KEYS[TX_POTION_MP_SMALL_COUNT] = {TX_POTION_MP_SMALL};

#define TX_POTION_MP_MEDIUM_COUNT 1
static int TX_POTION_MP_MEDIUM_KEYS[TX_POTION_MP_MEDIUM_COUNT] = {TX_POTION_MP_MEDIUM};

#define TX_POTION_MP_LARGE_COUNT 1
static int TX_POTION_MP_LARGE_KEYS[TX_POTION_MP_LARGE_COUNT] = {TX_POTION_MP_LARGE};
