#pragma once
#include "libgame_defines.h"

// Weapons
#define TX_SWORD_COUNT 3
static int TX_SWORD_KEYS[TX_SWORD_COUNT] = {TX_SWORD_00, TX_ACTION_SLASH_SWORD_F, TX_ACTION_SLASH_SWORD_B};

#define TX_DAGGER_COUNT 3
static int TX_DAGGER_KEYS[TX_DAGGER_COUNT] = {TX_DAGGER, TX_ACTION_SLASH_DAGGER_F, TX_ACTION_SLASH_DAGGER_B};

#define TX_AXE_COUNT 3
static int TX_AXE_KEYS[TX_AXE_COUNT] = {TX_AXE, TX_ACTION_SLASH_AXE_F, TX_ACTION_SLASH_AXE_B};

//#define TX_BOW_COUNT 4
//static int TX_BOW_KEYS[TX_BOW_COUNT] = {TX_BOW, TX_ACTION_SHOT_BOW_F, TX_ACTION_SHOT_BOW_B, TX_ACTION_SHOT_BOW_B_HALFLING_GOBLIN_DWARF};

//#define TX_TWO_HANDED_SWORD_COUNT 1
//static int TX_TWO_HANDED_SWORD_KEYS[TX_TWO_HANDED_SWORD_COUNT] = {TX_TWO_HANDED_SWORD};
//static int TX_TWO_HANDED_SWORD_KEYS[TX_TWO_HANDED_SWORD_COUNT] = {TX_TWO_HANDED_SWORD_00, TX_ACTION_SLASH_SWORD_F, TX_ACTION_SLASH_SWORD_B};

//#define TX_WARHAMMER_COUNT 1
//static int TX_WARHAMMER_KEYS[TX_WARHAMMER_COUNT] = {TX_WARHAMMER};

//#define TX_WHIP_COUNT 1
//static int TX_WHIP_KEYS[TX_WHIP_COUNT] = {TX_WHIP};
