#pragma once

#include "libgame_defines.h"
#include "texture_ids.h"

#define TX_WOLF_COUNT 12
static int TX_WOLF_KEYS[TX_WOLF_COUNT] = {
    TX_MONSTER_WOLF_IDLE,
    TX_MONSTER_WOLF_IDLE_SHADOW,
    TX_MONSTER_WOLF_WALK,
    TX_MONSTER_WOLF_WALK_SHADOW,
    TX_MONSTER_WOLF_ATTACK,
    TX_MONSTER_WOLF_ATTACK_SHADOW,
    TX_MONSTER_WOLF_JUMP,
    TX_MONSTER_WOLF_JUMP_SHADOW,
    TX_MONSTER_WOLF_DMG,
    TX_MONSTER_WOLF_DMG_SHADOW,
    TX_MONSTER_WOLF_DIE,
    TX_MONSTER_WOLF_DIE_SHADOW,
};


#define TX_BAT_COUNT 10
static int TX_BAT_KEYS[TX_BAT_COUNT] = {
    TX_MONSTER_BAT_IDLE,
    TX_MONSTER_BAT_IDLE_SHADOW,
    TX_MONSTER_BAT_ATTACK,
    TX_MONSTER_BAT_ATTACK_SHADOW,
    TX_MONSTER_BAT_DMG,
    TX_MONSTER_BAT_DMG_SHADOW,
    TX_MONSTER_BAT_SLEEP,
    TX_MONSTER_BAT_SLEEP_SHADOW,
    TX_MONSTER_BAT_DIE,
    TX_MONSTER_BAT_DIE_SHADOW,
};


#define TX_WARG_COUNT 12
static int TX_WARG_KEYS[TX_WARG_COUNT] = {
    TX_MONSTER_WARG_IDLE,
    TX_MONSTER_WARG_IDLE_SHADOW,
    TX_MONSTER_WARG_WALK,
    TX_MONSTER_WARG_WALK_SHADOW,
    TX_MONSTER_WARG_ATTACK,
    TX_MONSTER_WARG_ATTACK_SHADOW,
    TX_MONSTER_WARG_JUMP,
    TX_MONSTER_WARG_JUMP_SHADOW,
    TX_MONSTER_WARG_DMG,
    TX_MONSTER_WARG_DMG_SHADOW,
    TX_MONSTER_WARG_DIE,
    TX_MONSTER_WARG_DIE_SHADOW,
};


#define TX_GREEN_SLIME_COUNT 8
static int TX_GREEN_SLIME_KEYS[TX_GREEN_SLIME_COUNT] = {
    TX_MONSTER_GREEN_SLIME_IDLE,
    TX_MONSTER_GREEN_SLIME_IDLE_SHADOW,
    TX_MONSTER_GREEN_SLIME_JUMP_ATTACK,
    TX_MONSTER_GREEN_SLIME_JUMP_ATTACK_SHADOW,
    TX_MONSTER_GREEN_SLIME_DMG,
    TX_MONSTER_GREEN_SLIME_DMG_SHADOW,
    TX_MONSTER_GREEN_SLIME_DIE,
    TX_MONSTER_GREEN_SLIME_DIE_SHADOW,
};


#define TX_RAT_COUNT 10
static int RAT_KEYS[TX_RAT_COUNT] = {
    TX_MONSTER_RAT_IDLE,
    TX_MONSTER_RAT_IDLE_SHADOW,
    TX_MONSTER_RAT_WALK,
    TX_MONSTER_RAT_WALK_SHADOW,
    TX_MONSTER_RAT_DMG,
    TX_MONSTER_RAT_DMG_SHADOW,
    TX_MONSTER_RAT_DIE,
    TX_MONSTER_RAT_DIE_SHADOW,
    TX_MONSTER_RAT_ATTACK,
    TX_MONSTER_RAT_ATTACK_SHADOW,
};

#define TX_SKELETON_COUNT 10
static int SKELETON_KEYS[TX_SKELETON_COUNT] = {
    TX_MONSTER_SKELETON_IDLE,
    TX_MONSTER_SKELETON_IDLE_SHADOW,
    TX_MONSTER_SKELETON_WALK,
    TX_MONSTER_SKELETON_WALK_SHADOW,
    TX_MONSTER_SKELETON_DMG,
    TX_MONSTER_SKELETON_DMG_SHADOW,
    TX_MONSTER_SKELETON_DIE,
    TX_MONSTER_SKELETON_DIE_SHADOW,
    TX_MONSTER_SKELETON_ATTACK,
    TX_MONSTER_SKELETON_ATTACK_SHADOW,
};

#define TX_ZOMBIE_COUNT 10
static int ZOMBIE_KEYS[TX_ZOMBIE_COUNT] = {
    TX_MONSTER_ZOMBIE_IDLE,
    TX_MONSTER_ZOMBIE_IDLE_SHADOW,
    TX_MONSTER_ZOMBIE_WALK,
    TX_MONSTER_ZOMBIE_WALK_SHADOW,
    TX_MONSTER_ZOMBIE_DMG,
    TX_MONSTER_ZOMBIE_DMG_SHADOW,
    TX_MONSTER_ZOMBIE_DIE,
    TX_MONSTER_ZOMBIE_DIE_SHADOW,
    TX_MONSTER_ZOMBIE_ATTACK,
    TX_MONSTER_ZOMBIE_ATTACK_SHADOW,
};
