#pragma once

#include "libgame_defines.h"
#include "texture_ids.h"

#define TX_WOLF_COUNT 12
static int TX_WOLF_KEYS[TX_WOLF_COUNT] = {
    TX_WOLF_IDLE,
    TX_WOLF_IDLE_SHADOW,
    TX_WOLF_WALK,
    TX_WOLF_WALK_SHADOW,
    TX_WOLF_ATTACK,
    TX_WOLF_ATTACK_SHADOW,
    TX_WOLF_JUMP,
    TX_WOLF_JUMP_SHADOW,
    TX_WOLF_DMG,
    TX_WOLF_DMG_SHADOW,
    TX_WOLF_DIE,
    TX_WOLF_DIE_SHADOW,
};


#define TX_BAT_COUNT 10
static int TX_BAT_KEYS[TX_BAT_COUNT] = {
    TX_MONSTER_BAT_IDLE,
    TX_MONSTER_BAT_IDLE_SHADOW,
    TX_MONSTER_BAT_ATTACK,
    TX_MONSTER_BAT_ATTACK_SHADOW,
    TX_MONSTER_BAT_DMG,
    TX_MONSTER_BAT_DMG_SHADOW,
    TX_MONSTER_BAT_SLEEP,
    TX_MONSTER_BAT_SLEEP_SHADOW,
    TX_MONSTER_BAT_DIE,
    TX_MONSTER_BAT_DIE_SHADOW,
};


#define TX_WARG_COUNT 12
static int TX_WARG_KEYS[TX_WARG_COUNT] = {
    TX_WARG_IDLE,
    TX_WARG_IDLE_SHADOW,
    TX_WARG_WALK,
    TX_WARG_WALK_SHADOW,
    TX_WARG_ATTACK,
    TX_WARG_ATTACK_SHADOW,
    TX_WARG_JUMP,
    TX_WARG_JUMP_SHADOW,
    TX_WARG_DMG,
    TX_WARG_DMG_SHADOW,
    TX_WARG_DIE,
    TX_WARG_DIE_SHADOW,
};


#define TX_GREEN_SLIME_COUNT 8
static int TX_GREEN_SLIME_KEYS[TX_GREEN_SLIME_COUNT] = {
    TX_GREEN_SLIME_IDLE,
    TX_GREEN_SLIME_IDLE_SHADOW,
    TX_GREEN_SLIME_JUMP_ATTACK,
    TX_GREEN_SLIME_JUMP_ATTACK_SHADOW,
    TX_GREEN_SLIME_DMG,
    TX_GREEN_SLIME_DMG_SHADOW,
    TX_GREEN_SLIME_DIE,
    TX_GREEN_SLIME_DIE_SHADOW,
};
