#pragma once
#include "libgame_defines.h"

#define TX_HUMAN_COUNT 16
static int TX_HUMAN_KEYS[TX_HUMAN_COUNT] = {TX_CHAR_HUMAN_IDLE,
                                            TX_CHAR_HUMAN_IDLE_SHADOW,
                                            TX_CHAR_HUMAN_WALK,
                                            TX_CHAR_HUMAN_WALK_SHADOW,
                                            TX_CHAR_HUMAN_ATTACK,
                                            TX_CHAR_HUMAN_ATTACK_SHADOW,
                                            TX_CHAR_HUMAN_JUMP,
                                            TX_CHAR_HUMAN_JUMP_SHADOW,
                                            TX_CHAR_HUMAN_DMG,
                                            TX_CHAR_HUMAN_DMG_SHADOW,
                                            TX_CHAR_HUMAN_SPIN_DIE,
                                            TX_CHAR_HUMAN_SPIN_DIE_SHADOW,
                                            TX_CHAR_HUMAN_GUARD_SUCCESS,
                                            TX_CHAR_HUMAN_GUARD_SUCCESS_SHADOW,
                                            TX_CHAR_HUMAN_SHOT,
                                            TX_CHAR_HUMAN_SHOT_SHADOW};

#define TX_ORC_COUNT 14
static int TX_ORC_KEYS[TX_ORC_COUNT] = {
    TX_CHAR_ORC_IDLE,
    TX_CHAR_ORC_IDLE_SHADOW,
    TX_CHAR_ORC_WALK,
    TX_CHAR_ORC_WALK_SHADOW,
    TX_CHAR_ORC_ATTACK,
    TX_CHAR_ORC_ATTACK_SHADOW,
    TX_CHAR_ORC_JUMP,
    TX_CHAR_ORC_JUMP_SHADOW,
    TX_CHAR_ORC_DMG,
    TX_CHAR_ORC_DMG_SHADOW,
    TX_CHAR_ORC_DIE,
    TX_CHAR_ORC_DIE_SHADOW,
    TX_CHAR_ORC_GUARD_SUCCESS,
    TX_CHAR_ORC_GUARD_SUCCESS_SHADOW,
    //TX_ORC_SHOT,
    //TX_ORC_SHOT_SHADOW,
};


#define TX_ELF_COUNT 16
static int TX_ELF_KEYS[TX_ELF_COUNT] = {
    TX_CHAR_ELF_IDLE,
    TX_CHAR_ELF_IDLE_SHADOW,
    TX_CHAR_ELF_WALK,
    TX_CHAR_ELF_WALK_SHADOW,
    TX_CHAR_ELF_ATTACK,
    TX_CHAR_ELF_ATTACK_SHADOW,
    TX_CHAR_ELF_JUMP,
    TX_CHAR_ELF_JUMP_SHADOW,
    TX_CHAR_ELF_DMG,
    TX_CHAR_ELF_DMG_SHADOW,
    TX_CHAR_ELF_SPIN_DIE,
    TX_CHAR_ELF_SPIN_DIE_SHADOW,
    TX_CHAR_ELF_GUARD_SUCCESS,
    TX_CHAR_ELF_GUARD_SUCCESS_SHADOW,
    TX_CHAR_ELF_SHOT,
    TX_CHAR_ELF_SHOT_SHADOW,
};


#define TX_DWARF_COUNT 16
static int TX_DWARF_KEYS[TX_DWARF_COUNT] = {
    TX_CHAR_DWARF_IDLE,
    TX_CHAR_DWARF_IDLE_SHADOW,
    TX_CHAR_DWARF_WALK,
    TX_CHAR_DWARF_WALK_SHADOW,
    TX_CHAR_DWARF_ATTACK,
    TX_CHAR_DWARF_ATTACK_SHADOW,
    TX_CHAR_DWARF_JUMP,
    TX_CHAR_DWARF_JUMP_SHADOW,
    TX_CHAR_DWARF_DMG,
    TX_CHAR_DWARF_DMG_SHADOW,
    TX_CHAR_DWARF_SPIN_DIE,
    TX_CHAR_DWARF_SPIN_DIE_SHADOW,
    TX_DWARF_GUARD_SUCCESS,
    TX_DWARF_GUARD_SUCCESS_SHADOW,
    TX_CHAR_DWARF_SHOT,
    TX_CHAR_DWARF_SHOT_SHADOW,
};

#define TX_HALFLING_COUNT 16
static int TX_HALFLING_KEYS[TX_HALFLING_COUNT] = {
    TX_CHAR_HALFLING_IDLE,
    TX_CHAR_HALFLING_IDLE_SHADOW,
    TX_CHAR_HALFLING_WALK,
    TX_CHAR_HALFLING_WALK_SHADOW,
    TX_CHAR_HALFLING_ATTACK,
    TX_CHAR_HALFLING_ATTACK_SHADOW,
    TX_CHAR_HALFLING_JUMP,
    TX_CHAR_HALFLING_JUMP_SHADOW,
    TX_CHAR_HALFLING_DMG,
    TX_CHAR_HALFLING_DMG_SHADOW,
    TX_CHAR_HALFLING_SPIN_DIE,
    TX_CHAR_HALFLING_SPIN_DIE_SHADOW,
    TX_CHAR_HALFLING_GUARD_SUCCESS,
    TX_CHAR_HALFLING_GUARD_SUCCESS_SHADOW,
    TX_CHAR_HALFLING_SHOT,
    TX_CHAR_HALFLING_SHOT_SHADOW,
};

#define TX_GOBLIN_COUNT 16
static int TX_GOBLIN_KEYS[TX_GOBLIN_COUNT] = {
    TX_CHAR_GOBLIN_IDLE,
    TX_CHAR_GOBLIN_IDLE_SHADOW,
    TX_CHAR_GOBLIN_WALK,
    TX_CHAR_GOBLIN_WALK_SHADOW,
    TX_CHAR_GOBLIN_ATTACK,
    TX_CHAR_GOBLIN_ATTACK_SHADOW,
    TX_CHAR_GOBLIN_JUMP,
    TX_CHAR_GOBLIN_JUMP_SHADOW,
    TX_CHAR_GOBLIN_DMG,
    TX_CHAR_GOBLIN_DMG_SHADOW,
    TX_CHAR_GOBLIN_SPIN_DIE,
    TX_CHAR_GOBLIN_SPIN_DIE_SHADOW,
    TX_CHAR_GOBLIN_GUARD_SUCCESS,
    TX_CHAR_GOBLIN_GUARD_SUCCESS_SHADOW,
    TX_CHAR_GOBLIN_SHOT,
    TX_CHAR_GOBLIN_SHOT_SHADOW,
};
